name: CI

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - dev

env:
  WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'                # set this to the node version to use

jobs:
  lint-build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install
      run: npm install
    - name: npm run lint
      run: npm run lint
    - name: npm run build
      run: npm run build
